# Exercice 1 : les constructeurs

In [3]:
import numpy as np

In [36]:
#1. Constructeur un tableau numpy qui contient les éléments suivants : 1,5,7,8.
tab = np.array([1,5,7,8])

In [37]:
"""2. Constructeur un tableau numpy qui contient les éléments suivants :
1,2,3,4,5,6,7,8,9"""
tab1 = np.array([1,2,3,4,5,6,7,8,9])

In [38]:
#3. Créer un tableau de 10 éléments rempli de 0
tab_zeros = np.zeros(10,dtype="int32")
tab_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
#4. Créer un tableau de 2 lignes 5 colonnes rempli de 0
tab_ligne2_colonne5 = np.zeros([2,5],dtype="int32")
tab_ligne2_colonne5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
#5. Créer un tableau de 10 éléments rempli de 1
tab_ones = np.ones(10, dtype="int32")
tab_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
#6. Créer un tableau de 2 lignes 5 colonnes rempli de 1
tab_ones_2ligne_5colonne = np.ones([2,5],dtype="int32")
tab_ones_2ligne_5colonne

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
#7. Créer un tableau de 10 éléments rempli 8.5
tab_full = np.full(10, 8.5)
tab_full

array([8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5])

In [43]:
#8. Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus
tab_entiers = np.arange(1,10)
tab_entiers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
"""9. Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs
allant de 1 à 9 inclus
"""
tab_3ligne_3colonne = np.arange(1,10).reshape(3,3)
tab_3ligne_3colonne

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
#10.Créer une matrice identité de 4 lignes 4 colonnes
matrice_id4l4c = np.identity(4, dtype="int32")
matrice_id4l4c

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [46]:
#11. Tableau rempli de valeurs aléatoires normales centrées en zéro
tab_alea = np.linspace(-5,5,5, dtype="int")
tab_alea

array([-5, -2,  0,  2,  5])

In [47]:
"""12.Créer un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et
10
"""
tab_alea_entre1_10 = np.random.randint(2,10,20)
tab_alea_entre1_10

array([9, 5, 2, 9, 5, 3, 6, 8, 5, 7, 3, 4, 9, 9, 2, 3, 8, 3, 6, 3])

In [48]:
#13.Transformer le tableau précédent en matrice de 4 lignes et 5 colonnes
transf_tab = tab_alea_entre1_10.reshape(4,5)
print(transf_tab)

[[9 5 2 9 5]
 [3 6 8 5 7]
 [3 4 9 9 2]
 [3 8 3 6 3]]


In [49]:
"""14.Créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude
égale"""
tab_5ele = np.linspace(0,1,5)
tab_5ele

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Exercice 2 : les attributs d'un tableau numpy

In [50]:
#Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]]).
#1. Afficher le nombre de lignes et de colonnes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape


(3, 3)

In [51]:
#2. Afficher la dimension de mon tableau
a.ndim

2

In [52]:
#3. Afficher le nombre d'élément de mon tableau
a.size

9

In [53]:
#4. Afficher le type des éléments du tableau
a.dtype

dtype('int32')

# Exercice 3 : Indexing, slicing, subsetting, masking

In [4]:
#Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]]).
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
#1. afficher la valeur 5 qui est dans le tableau
b=a[1][1]
b

5

In [11]:
b=a[1,1]
b

5

In [56]:
#2. Remplacer le 5 qui est dans le tableau par 0
b=a[1][1]=0
Remplace =a
Remplace

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [13]:
autre=a[a==5]=0
autre

0

In [57]:
#3. afficher les chiffres 3, 6 et 9 du tableau
trois =a[0][2]
six =a[1][2]
neuf =a[2][2]
print(trois, six, neuf)

3 6 9


In [14]:
autre1=a[:,2]
autre1

array([3, 6, 9])

In [18]:
"""4. créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiers
aléatoires compris entre 0 et 9
"""
tab12 = np.random.randint(1,9,12).reshape(4,3)
tab12

array([[1, 1, 7],
       [6, 6, 7],
       [7, 8, 1],
       [8, 5, 1]])

In [20]:
tab12autre = np.random.randint(1,9,(4,3))
tab12autre

array([[5, 4, 5],
       [2, 2, 4],
       [2, 6, 8],
       [6, 8, 4]])

In [59]:
#5. Vérifier qu’il y a des nombres inférieur à 5
nb_inf = tab12 < 5
nb_inf

array([[ True, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [67]:
#6. Remplacer les nombres inférieurs à 5 par 0
remplacer_inf = tab12[tab12 < 5]= 0
tab12

array([[0, 5, 0],
       [7, 0, 0],
       [6, 0, 0],
       [9, 7, 0]])

# Exercice 4 :

In [113]:
"""1.Créer un tableau rempli de 11 nombres entiers
aléatoires compris entre 0 et 9"""
tab_1dimension = np.random.randint(1,9,11)
tab_1dimension

array([7, 4, 6, 4, 6, 3, 4, 6, 1, 4, 6])

In [114]:
#2. Ajouter le chiffre 3 à la fin du tableau à une dimension
dimension = np.append(tab_1dimension,3)
dimension

array([7, 4, 6, 4, 6, 3, 4, 6, 1, 4, 6, 3])

In [115]:
"""4.Créer un tableau de 4 lignes et 3 colonnes rempli de 11 nombres entiers
aléatoires compris entre 0 et 9"""
dimension.reshape(4,3)

array([[7, 4, 6],
       [4, 6, 3],
       [4, 6, 1],
       [4, 6, 3]])

In [117]:
#3. Quel est le type des éléments du tableau ?
dimension.dtype

dtype('int32')

In [118]:
#3. Changer de type des éléments du tableau en float32
changertype = dimension.astype('float32')
changertype.dtype

dtype('float32')

In [120]:
#5. Transformer le tableau en matrice dénommée “a” de 3 lignes et 4 colonnes
a = changertype.reshape(3,4)
a

array([[7., 4., 6., 4.],
       [6., 3., 4., 6.],
       [1., 4., 6., 3.]], dtype=float32)

In [98]:
"""6. Créer une matrice dénommée “b” de 3 lignes et 4 colonnes remplie de série
d'entiers successifs allant de 1 à 12 inclus
"""
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
"""7. Créer une matrice dénommée “c” qui est la concaténation des deux tableaux
“a” et “b” dans le sens horizontale"""
c = np.concatenate((a,b),axis=1)
c

array([[ 7.,  4.,  6.,  4.,  1.,  2.,  3.,  4.],
       [ 6.,  3.,  4.,  6.,  5.,  6.,  7.,  8.],
       [ 1.,  4.,  6.,  3.,  9., 10., 11., 12.]])

In [122]:
"""8. Créer une matrice dénommée “d” qui est la concaténation des deux tableaux
“a” et “b” dans le sens vertical"""
d = np.concatenate((a,b),axis=0)
d

array([[ 7.,  4.,  6.,  4.],
       [ 6.,  3.,  4.,  6.],
       [ 1.,  4.,  6.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [123]:
#9. Aplatir un tableau “d”
aplatir = d.flatten()
aplatir

array([ 7.,  4.,  6.,  4.,  6.,  3.,  4.,  6.,  1.,  4.,  6.,  3.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [124]:
#10.Supprimer dernier élément du tableau
supprimer =np.delete(aplatir,-1)
supprimer

array([ 7.,  4.,  6.,  4.,  6.,  3.,  4.,  6.,  1.,  4.,  6.,  3.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

# Exercice : Statistique avec numpy

In [22]:
#1. Afficher la somme des éléments du tableau
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(a)

45

In [83]:
#2. Afficher la somme des éléments du tableau par colonne
np.sum(a,axis=1)

array([ 6, 15, 24])

In [24]:
#3. Afficher la somme des éléments du tableau par ligne
np.sum(a,axis=1)

array([ 6, 15, 24])

In [23]:
#4. Afficher le produit des éléments du tableau par colonne
np.prod(a,axis=0)

array([ 28,  80, 162])

In [86]:
#5. Afficher le minimum du tableau
np.min(a)

1

In [87]:
#6. Afficher le maximum des éléments du tableau
np.max(a)

9

In [88]:
#7. Afficher la moyenne des éléments du tableau
np.mean(a)

5.0

In [89]:
#8. Afficher la variance des éléments du tableau
np.var(a)

6.666666666666667

In [90]:
#9. Afficher l’écart type des éléments du tableau
np.std(a)

2.581988897471611