In [ ]:

poids = int(input("Entrer le poids :"))
taille = float(input("Entrer la taille :"))

def imc(poids , taille):
    imc = poids/taille**2
    
    if imc<= 18.5:
        print("poids insuffisant")
    elif 18.5<imc<25:
        print("Corpulence normale")
    elif 25<imc<30:
        print("Surpoids")
    elif 30<imc<35:
        print("Obésité moderée")
    elif 35<imc<40:
        print("Obésité sevère")
    elif imc>=40:
        print("Obésité morbide")
    
    return imc

    
imc(poids, taille)

In [ ]:

nombreNote = int(input("Entrer un le nombre : "))
i = 0
liste = []

def afficheLesNote(nombreNote,i,liste):
    
    while i < nombreNote:
        Note =int(input("Entrer une note : "))
        liste.append(Note)
        print("note :",liste)
        i+=1
        print(liste.sort(reverse = True))
        print("Affiche les notes de manière decroissante :",liste )
    return afficheLesNote
afficheLesNote(nombreNote,i,liste)
    
def moyenne():
    calcul = sum(liste)
    moyenne = calcul/len(liste)
    print("la moyenne est : ",moyenne)
    return moyenne
    
moyenne()

In [ ]:
liste = [15,8,9,14,23,6,12]

for valeur in range(5):
    print(valeur)

In [ ]:
def produit(liste):
    a=1
    for i in liste:
        a = a*i
    return a

liste = [4,2,3]
produit(liste)
        

In [ ]:
n = int(input("Entrer un nombre : "))
def factoriel(n):
    i = 1
    
    if n>=0 :
        for pc in range(0,n):
            i = i*(pc+1)
        print("factorielle de ",n,"! ","est ",i)
           
    else:
        while n < 0:
            n = int(input("Entrer un nombre : "))
        if n>=0:
            for pc in range(0,n):
                i = i*(pc+1)
            print("factorielle de ",n,"! ","est ",i)
                
factoriel(n)

In [2]:
N =int(input("Entrer un nobre : "))
def nb_impair(N):
    i = 0
    liste = []
    while i < N:
        i+=1
        if(i%2 != 0):
            liste.append(i)
    print("la liste des nombres impair dans ",N, "est",liste)
    return nb_impair

nb_impair(N)

Entrer un nobre : 156
la liste des nombres impair dans  156 est [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155]


<function __main__.nb_impair(N)>

In [3]:
N=int(input("Entrer un nombre : "))
def nombre_impair(N):
    liste = []
    
    for a in range(N):
        a+=1
        if(a%2 !=0):
            liste.append(a)
    print(liste)
                  
nombre_impair(N)


    

Entrer un nombre : 256
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255]


In [ ]:
liste = [17,38,10,25,72]
liste.sort()
print("le tri est : ",liste)

liste.append(12)
print("la liste avec l'element 12 est : ",liste)

liste.sort(reverse=True)
print("la liste inversée est : ",liste)

print("le nombre l'element de la liste est : ",len(liste))

del liste[1]
print("Après avoir supprimer l'element 38 la liste est : ",liste)

print("le 2 et 3e element sont : ", liste[1:3])

print("le debut au 2e element sont : ", liste[0:2])

print("le 3e à la fin est : ",liste[2:5])




In [ ]:
a = int(input("Entrer le nombre de nombre que vous voulez : "))
def Doublons(a):
    n = 0
    liste = []
    while n < a:
        b = int(input("Entrer un nombre : "))
        liste.append(b)
        n+=1
    print("la liste initiale est : ",liste)
    doublons = list(set(liste))
    print("la liste finale est : ",doublons)
    
Doublons(a)
    

In [54]:
"""2- On créer un tableau 1 3 5 7 9 
* On affiche le nombre d'élément du tableau 
* On affiche le type des éléments contenu dans le tableau 
* On affiche le type du tableau
* On affiche le nombre de dimension du tableau
* On modifie le tableau qu'on vient de créer (remplacer 1 par 0, 9 par 6 )
* tous les éléments du tableau qui est inférieur à 5 on met à moins -1
* Affiche la moyenne des éléments du tableau
* La somme des éléments du tableau 
* Créer un tableau de 9 éléments remplient de 0
* Créer un tableau de 9 éléments remplient de 5,5
* Créer un tableau de 9 éléments remplient de 1
NB: On créer un tableau à une dimension et deux dimensions"""

import numpy as n
# On créer un tableau 1 3 5 7 9
tab_nb = n.array([1,3,5,7,9])


In [55]:

# On affiche le nombre d'élément du tableau
ele_tab= n.size(tab_nb) 
print("le nombre d'élement du tableau est : ",ele_tab)

le nombre d'élement du tableau est :  5


In [57]:
#On affiche le type des éléments contenu dans le tableau
tab_nb.dtype

dtype('int32')

In [58]:
#On affiche le type du tableau
type(tab_nb)

numpy.ndarray

In [59]:
#On affiche le nombre de dimension du tableau
tab_nb.ndim

1

In [60]:
#On modifie le tableau qu'on vient de créer (remplacer 1 par 0, 9 par 6 )
tab_nb[tab_nb==1]=0
tab_nb[tab_nb==9]=6
tab_nb

array([0, 3, 5, 7, 6])

In [61]:
#tous les éléments du tableau qui est inférieur à 5 on met à moins -1
tab_nb[tab_nb < 5] =-1
tab_nb

array([-1, -1,  5,  7,  6])

In [64]:
#Affiche la moyenne des éléments du tableau
moyenne = n.mean(tab_nb)
moyenne

3.2

In [65]:
#La somme des éléments du tableau
somme = sum(tab_nb)
somme

16

In [68]:
#Créer un tableau de 9 éléments remplient de 
tab_z= n.zeros(9,dtype ="int32")
tab_z

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
tab_z = n.zeros((2,9),dtype="int32")
tab_z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [74]:
#Créer un tableau de 9 éléments remplient de 5,5
tab_cinq = n.full(9,5.5)
tab_cinq

array([5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5])

In [79]:
tab_cinq = n.full((2,9),5.5)
tab_cinq

array([[5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5]])

In [80]:
#Créer un tableau de 9 éléments remplient de 1
tab_un = n.full(9,1)
tab_un

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [81]:
tab_un = n.full((2,9),1)
tab_un

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [19]:
import numpy as np
import random

tab = np.random.randint(0,200,7)
print(tab)

[ 26  43 112   6  14 168 146]


In [20]:
mat_Tab = np.ones([4,4],dtype=float)
print(mat_Tab)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [59]:
mat_Tab = np.ones([4,4],dtype="int32")
mat_Tab

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [4]:
multi = mat_Tab*4
multi

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [5]:
matrice = np.dot(multi,np.diag([2,4,6,8]))
matrice

array([[ 8, 16, 24, 32],
       [ 8, 16, 24, 32],
       [ 8, 16, 24, 32],
       [ 8, 16, 24, 32]])

In [9]:
import numpy as np

In [82]:
N = int(input("Entrer un nombre : "))
i=0
liste = []


while i<N:
    a = int(input("Entrer : "))
    liste.append(a)
    tab = np.array(liste,dtype="int32")
    i+=1
    

tab

Entrer un nombre : 7
Entrer : 8
Entrer : 6
Entrer : 12
Entrer : 36
Entrer : 7
Entrer : 9
Entrer : 2


array([ 8,  6, 12, 36,  7,  9,  2])

In [88]:
N = int(input("Entrer le nombre de nombre que vous voulez rentrer : "))
liste = []
for i in range(N):
    a = int(input("Entrer un nombre :"))
    liste.append(a)
    tab = np.array(liste,dtype="int32")
tab
    


Entrer le nombre de nombre que vous voulez rentrer : 5
Entrer un nombre :7
Entrer un nombre :9
Entrer un nombre :2
Entrer un nombre :5
Entrer un nombre :3


array([7, 9, 2, 5, 3])